### ISSUE TITLE
Option to allow breakpoints up

### ISSUE THREAD

**Issue by mattgrannary** [ehellman/react-breakpoints#10]
This is more of a feature request.

In my experience I've found that breakpoints are more intuitive if they break in an upward direction instead of down. Mainly because there is an obviously definitive bottom but no real ceiling. This also aligns with the mobile first ideology.

Are there any plans on implementing an option for this?

**Comment by ehellman** [comment]
Hey @mattgrannary.

I am not sure exactly what you mean here, since all the media queries (except the first) is `min-width` I consider that to be an upward direction without a ceiling.

If you want to flip how it works right now with a prop I am completely open to that, but I need to know what you have in mind so that I understand the problem you are having :)

**Comment by ehellman** [comment]
```
const bps = {
  mobile: 320,
  mobileLandscape: 480,
  tablet: 768,
  tabletLandscape: 1023
}
```

If the viewPort size is between 480 and 768, do you imagine it hitting the `tablet` breakpoint?

**Comment by mattgrannary** [comment]
Actually, I think I was looking at this wrong. If I set my smallest breakpoint to 0 then it works as I was expecting. This way anything between 0 and 320 for example would be the smallest.

**Comment by mattgrannary** [comment]
I'm naming the breakpoints a little differently than your example. I have keys like `xs`, `sm`, `md`, `lg` and `xl`. So I'd expect that anything between 0 and 320 would be `xs`.

**Comment by ehellman** [comment]
@mattgrannary The logic today is as follows, assuming these are your breakpoints:
```
const bps = {
  mobile: 320,
  mobileLandscape: 480,
  tablet: 768,
  tabletLandscape: 1023
}
```

| Viewport width  | currentBreakpoint |
| ------------- | ------------- |
| 100px | mobile  |
| 280px  | mobile  |
| 380px  | mobile  |
| 535px  | mobileLandscape  |
| 768px  | tablet  |
| 1080px  | tabletLandscape  |
| 1920px  | tabletLandscape  |
| 2560px  | tabletLandscape  |

So everything between `0` and the size of your **SECOND** breakpoint will set `currentBreakpoint` to the first breakpoint in your list. So you do not have to set your smallest `xs` breakpoint to `0`, it should behave as you expect even if you set it to 320, as long as you are okay with `xs` still being the `currentBreakpoint` all the way until it hits the value of the second breakpoint.

... Unless I misunderstood you of course! Just want to make sure that your problem is solved! :) Let me know if you still want me to add something or have more questions!

**Comment by ehellman** [comment]
![image](https://user-images.githubusercontent.com/586152/43525669-bef8f1de-95a2-11e8-9675-fefb52d60e29.png)

**Comment by mattgrannary** [comment]
After some testing, I seem to be able to achieve this affect by setting the breakpoints like this:

```javascript
const breakpoints = {
    xs: 0,
    sm: 321,
    md: 451,
    lg: 769,
    xl: 1281
}
```

Setting the first breakpoint to 0 is basically a noop because, as you've stated, anything below the first and up to the second is considered one breakpoint. I've also shifted my breakpoints up by one step and added one pixel to each. This means that I get the `xs` breakpoint for widths between 0 - 320, the `sm` breakpoint for widths between 321 - 450, the `md` breakpoint between 451 - 768, the `lg` breakpoint between 769 - 1280 and the `xl` from 1281 and up.

**Comment by ehellman** [comment]
@mattgrannary Great find! However, I could add this as an option if you like?

```
<ReactBreakpoints
  breakpoints={breakpoints}
  mediaQueriesBreakUpwards={true}
>
  ...
```

... or something like that! :) It would be a pretty minor change.

**Comment by ehellman** [comment]
Taking note of your example with a breakpoint set to 0, will work this into the README in the future and consider enabling the reversal of breaking via a prop. Thanks for the feedback! :)
