### ISSUE TITLE
Ordering breakpoints from high to low, seems to break this package?

### ISSUE THREAD

**Issue by kfayelun** [ehellman/react-breakpoints#25]
Hey,
I tested another breakpoint-library before this, and had my breakpoints listed from high-to-low instead of low-to-high, as in your docs. This breaks react-breakpoints, as the breakpoint logic just takes the breakpoint array, reverses it combined with a null check, and then categorizes without actually testing the number size further (from what I can see). From calculateBreakpoint():
      var breakpointValue = _this2.props.breakpoints[breakpoint];
      if (!currentBreakpoint && screenWidth >= breakpointValue) {
        currentBreakpoint = breakpoint;
      }
Seems like something that can very easily break to me, with a dev just adding another format at the end of the list or with someone quickly and somewhat haphazardly throwing the list together.

**Comment by ehellman** [comment]
Hello @kfayelun, thank you so much for opening an issue! Sorry for the delay. As I described in another issue I have been dealing with some health issues which I have recovered from so I am back to maintaining this package but adding more maintainers to speed up response time.

As for your question, yes, this is correct. So your suggestion is that we add some logic that takes the props passed and sort them according to size, as a failsafe for user error?

I am not opposed to this, just thinking about what the best solution would be for this issue. If it is to:
- Clean up passed breakpoints object and sort it, store locally and use this object instead for operations. But that we just do this once and don't update the object if new props are passed (breakpoints will become dynamic, which might introduce a whole heap of problems)

If you have a suggestion for a solution please feel free to share your idea, otherwise I might take a look at this tomorrow and post here, but it's currently at the bottom of my list. However issues such as this one (making the package harder to break but keeping it simple) will be my highest priority before adding new features.

**Comment by ehellman** [comment]
#23 solves this, if you don't agree please re-open the issue! Will get merged as soon as the author replies back and included in `3.0.4`

**Comment by kfayelun** [comment]
Hey! So sorry for my late reply here, I was in the middle of something and then totally forgot this. Yes, it looks like this fixes things, thanks for your feedback!
