### ISSUE TITLE
Pull request open for 21 days

### ISSUE THREAD

**Issue by joetidee** [ehellman/react-breakpoints#26]
Hello,

There has been a pull request open for 21 days. We really need this merged. Can you please look at this ASAP or allow myself to approve the merge?

https://github.com/ehellman/react-breakpoints/pull/24

**Comment by ehellman** [comment]
Hi @joetidee.

Sorry for the super late response but I have been dealing with a serious health problem since august which I have now recovered from. Or, I'm at 90% capacity at least and am back to somewhat normal.

During this period I've actually thought about reaching out to 2 people, including you, for this exact reason. Could you please send an e-mail to iam@erikhellman.com so that we can get in touch. Would be great if you could include your preferred mode of speaking in the e-mail!

As for the pull request I will read through the issues today and make sure to get to the pull requests tomorrow (friday). So within 20 hours from posting this basically :) Have to restore my SSH keys and do some catching up tonight.
