### ISSUE TITLE
Unable to get ref of the actual component

### ISSUE THREAD

**Issue by intositeme** [ehellman/react-breakpoints#8]
When trying to access my component from the parent using refs, returns undefined.

**Comment by intositeme** [comment]
https://codesandbox.io/s/6lvrw7x59n
Did a quick sample here. 
It doesn't really show my use case, but i need to access my component from the parent.

**Comment by ehellman** [comment]
@intositeme Thank you so much for taking the time to create an example, it will help a lot!

I have decided to postpone 3.0 until at least June 10th so that I can take a look at this issue and include it in the release. I think it's as easy as wrapping the `WrappedComponent` in a `class`, but we'll see :)

Reporting back as soon as this is resolved!

**Comment by ehellman** [comment]
Fixed in https://github.com/ehellman/react-breakpoints/pull/7/commits/1010aa8be84e6e64577e4d786e6f72e1d6a856c4

Reviewing docs now, then merging and publishing 3.0, so be on the lookout for an update, it will solve your issue :)
